### ISSUE TITLE
Logic error when parsing header data

### ISSUE THREAD

**Issue by Jhynjhiruu** [bigbass1997/nust64#2]
I'm using nust64 to parse an N64 ROM's header, since I couldn't be bothered to write my own parser. There appears to be an issue when reading the fields `image_name` and `unknown2`: reading the previous values advances the data buffer, calling `data.advance()` further advances the data buffer, and then `data.slice()` panics with an out-of-range error.
You could fix this with something like this:
```rust
image_name: {
  let slc = data.slice(..20)[..].try_into().unwrap();
  data.advance(20);
  slc
},
```
but I'm too scared to submit a pull request.

**Comment by bigbass1997** [comment]
Thanks for reporting this. Guess I must not have tested that heh. Should work now.
